#!/bin/sh

set -eu

cd "$(dirname "$0")"
cd "$(git rev-parse --show-toplevel)"

version="$(cat info.json | jq -r .version)"
output="BatteryLocomotive_${version}.zip"
prefix="BatteryLocomotive_${version}/"

git archive HEAD --output="$output" --prefix="$prefix"

echo "Build $output"
